const { SensePeopleGoal } = require('../intentions/Occupation')
const Person = require('../Observables/Person')
const Clock = require('../utils/Clock')
const { house, houseAgent, botAgent } = require('./HouseAndAgents')

house.people.eve = new Person(house, 'Eve', 'null')
houseAgent.beliefs.declare('in_room eve null')
houseAgent.postSubGoal(new SensePeopleGoal({ people: Object.values(house.people) }))

//schedule

// Simulated Daily/Weekly schedule
Clock.global.observe('mm', (mm) => {
    var time = Clock.global
    if (time.hh == 0 && time.mm == 5)
        house.devices.lights.bedroom_light.switchOffLightOverride()
    if (time.hh == 9 && time.mm == 0)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 9 && time.mm == 0)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 9 && time.mm == 5)
        house.people.alice.moveTo('bathroom')
    if (time.hh == 9 && time.mm == 5)
        house.devices.curtains.livingroom_curtains.closeCurtains()
    if (time.hh == 9 && time.mm == 5)
        house.people.bob.moveTo('bathroom')
    if (time.hh == 9 && time.mm == 10)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 9 && time.mm == 15)
        house.people.bob.moveTo('kitchen')
    if (time.hh == 9 && time.mm == 20)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 9 && time.mm == 25)
        house.people.alice.moveTo('kitchen')
    if (time.hh == 10 && time.mm == 0)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 10 && time.mm == 5)
        house.people.bob.moveTo('garage')
    if (time.hh == 10 && time.mm == 20)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 11 && time.mm == 30)
        house.people.alice.moveTo('kitchen')
    if (time.hh == 12 && time.mm == 00)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 12 && time.mm == 5)
        house.people.bob.moveTo('kitchen')
    if (time.hh == 13 && time.mm == 15)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 13 && time.mm == 15)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 13 && time.mm == 20)
        house.people.bob.moveTo('entrance')
    if (time.hh == 13 && time.mm == 25)
        house.people.bob.moveTo('garden')
    if (time.hh == 13 && time.mm == 30)
        house.people.bob.moveTo('garage')
    if (time.hh == 13 && time.mm == 30)
        house.people.alice.moveTo('garage')
    if (time.hh == 13 && time.mm == 35)
        house.people.alice.moveTo('null')
    if (time.hh == 13 && time.mm == 35)
        house.people.bob.moveTo('null')
    if (time.hh == 16 && time.mm == 00)
        house.people.alice.moveTo('garage')
    if (time.hh == 16 && time.mm == 00)
        house.people.bob.moveTo('garage')
    if (time.hh == 16 && time.mm == 05)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 16 && time.mm == 05)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 16 && time.mm == 05)
        house.devices.heatings.livingroom_heating.startHeating()
    if (time.hh == 16 && time.mm == 10)
        house.people.alice.moveTo('bathroom')
    if (time.hh == 16 && time.mm == 15)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 16 && time.mm == 20)
        house.people.alice.moveTo('kitchen')
    if (time.hh == 16 && time.mm == 30)
        house.people.bob.moveTo('entrance')
    if (time.hh == 16 && time.mm == 30)
        house.devices.lights.kitchen_light.switchOnLightOverride()
    if (time.hh == 16 && time.mm == 30)
        house.devices.lights.entrance_light.switchOnLightOverride()
    if (time.hh == 16 && time.mm == 30)
        house.devices.lights.livingroom_light.switchOnLightOverride()
    if (time.hh == 16 && time.mm == 30)
        house.people.eve.moveTo('entrance')
    if (time.hh == 16 && time.mm == 35)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 16 && time.mm == 35)
        house.people.eve.moveTo('livingroom')
    if (time.hh == 16 && time.mm == 40)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 16 && time.mm == 45)
        house.people.alice.moveTo('kitchen')
    if (time.hh == 17 && time.mm == 30)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 17 && time.mm == 30)
        house.devices.heatings.livingroom_heating.stopHeating()
    if (time.hh == 18 && time.mm == 30)
        house.people.alice.moveTo('kitchen')
    if (time.hh == 18 && time.mm == 30)
        house.people.bob.moveTo('kitchen')
    if (time.hh == 18 && time.mm == 30)
        house.people.eve.moveTo('kitchen')
    if (time.hh == 20 && time.mm == 30)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 20 && time.mm == 30)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 20 && time.mm == 30)
        house.people.eve.moveTo('livingroom')
    if (time.hh == 20 && time.mm == 40)
        house.people.alice.moveTo('entrance')
    if (time.hh == 20 && time.mm == 40)
        house.people.bob.moveTo('entrance')
    if (time.hh == 20 && time.mm == 40)
        house.people.eve.moveTo('entrance')
    if (time.hh == 20 && time.mm == 45)
        house.people.alice.moveTo('garden')
    if (time.hh == 20 && time.mm == 45)
        house.people.bob.moveTo('garden')
    if (time.hh == 20 && time.mm == 45)
        house.people.eve.moveTo('garden')
    if (time.hh == 22 && time.mm == 30)
        house.people.alice.moveTo('entrance')
    if (time.hh == 22 && time.mm == 30)
        house.people.bob.moveTo('entrance')
    if (time.hh == 22 && time.mm == 30)
        house.people.eve.moveTo('null')
    if (time.hh == 22 && time.mm == 35)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 22 && time.mm == 35)
        house.people.bob.moveTo('livingroom')
})

Clock.global.observe('dd', (dd) => {
    if (dd === 1) {
        process.exit();
    }
})

// Start clock
Clock.startTimer()