const Clock = require('../utils/Clock')
const { house, houseAgent, botAgent } = require('./HouseAndAgents')

//schedule

// Simulated Daily/Weekly schedule
Clock.global.observe('mm', (mm) => {
    var time = Clock.global
    if (time.hh == 0 && time.mm == 5)
        house.devices.lights.bedroom_light.switchOffLightOverride()
    if (time.hh == 6 && time.mm == 0)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 6 && time.mm == 5)
        house.people.bob.moveTo('bathroom')
    if (time.hh == 6 && time.mm == 10)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 6 && time.mm == 15)
        house.people.bob.moveTo('kitchen')
    if (time.hh == 6 && time.mm == 20)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 6 && time.mm == 25)
        house.people.bob.moveTo('garage')
    if (time.hh == 6 && time.mm == 30)
        house.people.bob.moveTo('null')
    if (time.hh == 7 && time.mm == 0)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 7 && time.mm == 5)
        house.people.alice.moveTo('bedroom')
    if (time.hh == 7 && time.mm == 10)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 7 && time.mm == 15)
        house.people.alice.moveTo('bathroom')
    if (time.hh == 7 && time.mm == 20)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 7 && time.mm == 25)
        house.people.alice.moveTo('kitchen')
    if (time.hh == 7 && time.mm == 30)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 7 && time.mm == 35)
        house.people.alice.moveTo('garage')
    if (time.hh == 7 && time.mm == 45)
        house.people.alice.moveTo('null')
    if (time.hh == 13 && time.mm == 00)
        house.people.alice.moveTo('garage')
    if (time.hh == 13 && time.mm == 5)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 13 && time.mm == 10)
        house.people.alice.moveTo('bathroom')
    if (time.hh == 13 && time.mm == 15)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 13 && time.mm == 20)
        house.people.alice.moveTo('kitchen')
    if (time.hh == 14 && time.mm == 15)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 14 && time.mm == 30)
        house.people.alice.moveTo('bathroom')
    if (time.hh == 14 && time.mm == 45)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 15 && time.mm == 45)
        house.people.alice.moveTo('studio')
    if (time.hh == 18 && time.mm == 00)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 18 && time.mm == 00)
        house.people.bob.moveTo('garage')
    if (time.hh == 18 && time.mm == 05)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 18 && time.mm == 30)
        house.people.alice.moveTo('kitchen')
    if (time.hh == 18 && time.mm == 30)
        house.people.bob.moveTo('studio')
    if (time.hh == 19 && time.mm == 25)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 19 && time.mm == 30)
        house.people.bob.moveTo('kitchen')
    if (time.hh == 20 && time.mm == 30)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 20 && time.mm == 30)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 20 && time.mm == 35)
        house.people.alice.moveTo('bathroom')
    if (time.hh == 20 && time.mm == 50)
        house.people.bob.moveTo('bathroom')
    if (time.hh == 21 && time.mm == 0)
        house.people.alice.moveTo('livingroom')
    if (time.hh == 21 && time.mm == 0)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 21 && time.mm == 5)
        house.people.bob.moveTo('entrance')
    if (time.hh == 21 && time.mm == 10)
        house.people.bob.moveTo('garden')
    if (time.hh == 21 && time.mm == 15)
        house.people.bob.moveTo('entrance')
    if (time.hh == 21 && time.mm == 20)
        house.people.bob.moveTo('livingroom')
    if (time.hh == 23 && time.mm == 0)
        house.people.alice.moveTo('bedroom')
    if (time.hh == 23 && time.mm == 0)
        house.people.bob.moveTo('bedroom')
})

Clock.global.observe('dd', (dd) => {
    if (dd === 3) {
        process.exit();
    }
})

// Start clock
Clock.startTimer()